[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nexus_wallet = "G4vCcRCeB3rWpaTkkpsPWTf9Ar2a7qoWTJsWboztF6wS"
nexus_entry_point = "9tPUcx4o8kjtCioPepUqhBozAY3SjTGkgJyxfhxVJEHo"
nexus_paymaster = "CvPEv5QcxwH2k3S6YUuw9MtsfEEsWEUimFwnwHL7ytze"
nexus_bridge = "Hrhe54Vk1mRR2SXvyR33Y5xaNGzVYh3gXPcmGRFFVxQr"

[programs.devnet]
nexus_wallet = "G4vCcRCeB3rWpaTkkpsPWTf9Ar2a7qoWTJsWboztF6wS"
nexus_entry_point = "9tPUcx4o8kjtCioPepUqhBozAY3SjTGkgJyxfhxVJEHo"
nexus_paymaster = "CvPEv5QcxwH2k3S6YUuw9MtsfEEsWEUimFwnwHL7ytze"
nexus_bridge = "Hrhe54Vk1mRR2SXvyR33Y5xaNGzVYh3gXPcmGRFFVxQr"

[programs.mainnet]
nexus_wallet = "G4vCcRCeB3rWpaTkkpsPWTf9Ar2a7qoWTJsWboztF6wS"
nexus_entry_point = "9tPUcx4o8kjtCioPepUqhBozAY3SjTGkgJyxfhxVJEHo"
nexus_paymaster = "CvPEv5QcxwH2k3S6YUuw9MtsfEEsWEUimFwnwHL7ytze"
nexus_bridge = "Hrhe54Vk1mRR2SXvyR33Y5xaNGzVYh3gXPcmGRFFVxQr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/wallet",
    "programs/entry_point",
    "programs/paymaster", 
    "programs/bridge"
]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
bind_address = "0.0.0.0"
rpc_port = 8899
ws_port = 8900
limit_ledger_size = 10000
startup_wait = 5000

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[test.validator.account]
# Add any required accounts for testing here

[test.genesis]
# Add any genesis configuration here 