[package]
name = "svm-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-messages = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-program = "1.18.2"
bytemuck = "1.14.0"
borsh = "0.10.3" 